
export const products = [
    {
      id: '1',
      name: 'Floral Summer Dress',
      brand: 'Zara',
      price: 79.99,
      image: require('../assets/tshirt1.jpg'),
      description: 'Beautiful floral dress perfect for summer occasions.',
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      id: '2',
      name: 'Denim Jacket',
      brand: 'Levis',
      price: 129.99,
      image: require('../assets/tshirt2.jpg'),
      description: 'Classic denim jacket with modern styling.',
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      id: '3',
      name: 'Jacket',
      brand: 'Levis',
      price: 129.99,
      image: require('../assets/tshirt3.jpg'),
      description: 'Classic denim jacket with modern styling.',
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      id: '4',
      name: 'Trouser',
      brand: 'Levis',
      price: 129.99,
      image: require('../assets/tshirt4.jpg'),
      description: 'Classic denim jacket with modern styling.',
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      id: '5',
      name: 'Jacket',
      brand: 'Levis',
      price: 129.99,
      image: require('../assets/tshirt5.jpg'),
      description: 'Classic denim jacket with modern styling.',
      sizes: ['S', 'M', 'L', 'XL'],
    },
    {
      id: '6',
      name: 'DeJacket',
      brand: 'Levis',
      price: 129.99,
      image:require('../assets/tshirt6.jpg'),
      description: 'Classic denim jacket with modern styling.',
      sizes: ['S', 'M', 'L', 'XL'],
    },
]